motor_info = {
     'lego-ev3-l-motor': {'motion_type': 'rotation',
                          'count_per_rot': 360,
                          'max_speed': 1050,
                          'position_p': 80000,
                          'position_i': 0,
                          'position_d': 0,
                          'polarity': 'normal',
                          'speed_p': 1000,
                          'speed_i': 60,
                          'speed_d': 0 },
     'lego-ev3-m-motor': {'motion_type': 'rotation',
                          'count_per_rot': 360,
                          'max_speed': 1560,
                          'position_p': 160000,
                          'position_i': 0,
                          'position_d': 0,
                          'polarity': 'normal',
                          'speed_p': 1000,
                          'speed_i': 60,
                          'speed_d': 0 },
     'lego-nxt-motor':   {'motion_type': 'rotation',
                          'count_per_rot': 360,
                          'max_speed': 1020,
                          'position_p': 80000,
                          'position_i': 0,
                          'position_d': 0,
                          'polarity': 'normal',
                          'speed_p': 1000,
                          'speed_i': 60,
                          'speed_d': 0 },
     'fi-l12-ev3-50':    {'motion_type': 'linear',
                          'count_per_m': 2000,
                          'full_travel_count': 100,
                          'max_speed': 24,
                          'position_p': 40000,
                          'position_i': 0,
                          'position_d': 0,
                          'polarity': 'normal',
                          'speed_p': 1000,
                          'speed_i': 60,
                          'speed_d': 0,
                         },
     'fi-l12-ev3-100':   {'motion_type': 'linear',
                          'count_per_m': 2000,
                          'full_travel_count': 200,
                          'max_speed': 24,
                          'position_p': 40000,
                          'position_i': 0,
                          'position_d': 0,
                          'polarity': 'normal',
                          'speed_p': 1000,
                          'speed_i': 60,
                          'speed_d': 0,
                         }
}
